import type { Metadata } from 'next';
import { Providers } from './providers';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'], variable: '--font-main' });

export const metadata: Metadata = {
  title: 'JSHOP',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body className={`antialiased bg-background-light`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
