import type { Metadata } from 'next';
import { Providers } from './providers';
import './globals.css';
import { Reddit_Sans } from 'next/font/google';
import { Montserrat } from 'next/font/google';

const montserrat = Montserrat({ subsets: ['latin'], variable: '--font-main' });
const reddit_sans = Reddit_Sans({ subsets: ['latin'], variable: '--font-sub-header' });

export const metadata: Metadata = {
  title: 'JSHOP',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={` ${reddit_sans.variable} ${montserrat.variable}  min-h-screen`}>
      <body className={`antialiased bg-background-light`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
